### PR TITLE
compatibility with Windows newline format

### PR DESCRIPTION
**Pull request by pkasprzyk**

### CODE REVIEW

**Comment by HaaLeo** [comment]
Hi @pkasprzyk 
thx for your PR. I hope to be able to review it within the next couple of days.

**Comment by HaaLeo** [comment]
Hi @pkasprzyk can you please add a test where the file header contains windows line endings? I am thinking of people which prefer to use windows CRLF. Then the simple `content = stream.read().decode('utf-8').replace(os.linesep, '\n')` is probably not sufficient.

I think a project should generally decide whether it wants to use LF or CRLF for its source code files. Then imho it is up to the developers to setup their development environment. For example as a windows user working on a LF project you can alter your local line ending settings via the git CLI or the used editor / IDE. For example with VS Code one can easily set which line ending format should be used.

The more I am writing this comment I am sceptical whether this PR is needed or whether it's up to the developer team to decide on line endings and then set up their local dev environment.

**Review by HaaLeo — CHANGES_REQUESTED** [review]
Add test for a CRLF file header

**Comment by pkasprzyk** [comment]
@HaaLeo thanks for your comment!

I've added the test case, but after some thinking I changed the PR altogether, too. As for the rationale/context of this whole change:
`pylint`'s `node.stream()` outputs file contents in binary format, so "as-is". On the other hand, `open('r')` uses "universal newlines mode", which translates `\r\n` to `\n` and this causes a problem even if both header and source files use CRLF. 

This is doubly problematic if you're trying to automatically test you code on both linux and windows, because of git's `autocrlf` feature.

I've now changed `FileHeaderChecker.open()` to use binary mode, so both header and node are treated the same way (and contain whatever newline format is actually on fs).

**Review by HaaLeo — APPROVED** [review]

**Comment by HaaLeo** [comment]
Released in v0.3.2

**Pull request merged**
